'use client';
import {Label, Textarea} from 'flowbite-react';
import {revalidatePath} from 'next/cache';
import {Budget} from 'lib/data';
import {FormEvent, FormEventHandler, useState} from 'react';
import {EventCommentThreadController} from './review_actions';

// [This function was partially generated by copilot and then edited]
export function EventCommentThread({
  budget,
  eventCommentThreadController,
}: {
  budget: Budget;
  eventCommentThreadController: EventCommentThreadController;
}) {
  const [comment, setComment] = useState(eventCommentThreadController.comment.comment);

  const saveComment: FormEventHandler = async (e: FormEvent) => {
    e.preventDefault();
    eventCommentThreadController.comment.comment = comment;
    await eventCommentThreadController.addEventComment(
      budget,
      eventCommentThreadController.comment
    );
    revalidatePath(`/budget/${budget.id}`);
  };

  return (
    <div className="flex flex-col space-y-2">
      <Label>Deny Event</Label>
      <Textarea
        value={comment}
        placeholder={'Reason to deny event'}
        onChange={e => setComment(e.target.value)}
        onBlur={saveComment}
      />
    </div>
  );
}
